services:
  db:
    image: postgres:16
    container_name: bp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaa123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
